{
 "title": "zqd resources",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "zqd cpu usage rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{id=~\"/kube.+\",container=\"zqd\"}[1m])"
    },
    {}
   ]
  },
  {
   "title": "zqd tcp read bytes rate (Linkerd)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tcp_read_bytes_total{app_kubernetes_io_name=\"zqd\"}[1m]))"
    }
   ]
  },
  {
   "title": "zqd memory usage bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/kube.+\",container=\"zqd\"}"
    }
   ]
  },
  {
   "title": "zqd container network receive bytes rate (cAdvisor)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[1m]))"
    }
   ]
  }
 ]
}